-- queries to add tables

CREATE TABLE SHIPMENT_CONSISTS_OF (
Shipment_Number VARCHAR2(10) CONSTRAINT shipno_fk REFERENCES shipment,
ProductID VARCHAR2(50) CONSTRAINT prodid_fk REFERENCES products);
commit;


CREATE TABLE PRODUCTS_BELONG_TO (
ProductID VARCHAR2(50) CONSTRAINT productid_fk REFERENCES products,
CategoryID VARCHAR2(50) CONSTRAINT catid_fk REFERENCES subcategory);
commit;

CREATE TABLE DELIVERY (
TrackingNumber VARCHAR2(20) CONSTRAINT trackno_pk PRIMARY KEY,		
Carrier	VARCHAR2(20),	
Delivery_Date Date,		
Delivery_Person VARCHAR2 (50), 
Shipping_Address VARCHAR2 (50),		
Order_ID VARCHAR2(20) CONSTRAINT delivery_fk REFERENCES Orders
);
commit;


CREATE TABLE ORDERS (
OrderID VARCHAR2(20) CONSTRAINT orderid_pk PRIMARY KEY, 
Orderitem VARCHAR2(50)CONSTRAINT orderitem_nn NOT NULL,		
CustomerID	VARCHAR2(20) CONSTRAINT custid_fk REFERENCES Customers,	
PaymentID VARCHAR2(20) CONSTRAINT paymentid_fk REFERENCES Payments,
OrderDate TIMESTAMP,	
OrderStatus VARCHAR2(50) CONSTRAINT orderstatus_nn CHECK (OrderStatus IN ('Placed', 'Pending', 'Canceled'))
);
commit;


CREATE TABLE PAYMENTS(
PaymentID VARCHAR2(20) CONSTRAINT paymentid_pk PRIMARY KEY, 	
Paymentdate TIMESTAMP,		
Payment_Method VARCHAR2(20) CONSTRAINT method_nn CHECK (Payment_Method IN ('Credit Card', 'Cash', 'PayPal')),		
Payment_Amount NUMBER (10,2) CONSTRAINT amount_pos CHECK (Payment_Amount > 0),	
Tax NUMBER (4,2),
Discount NUMBER (4,2),	
EmployeeID VARCHAR2(50) CONSTRAINT empid_fk REFERENCES Employees,
Payment_Status VARCHAR2(50) CONSTRAINT status_nn CHECK (Payment_Status IN ('Paid', 'Pending', 'Failed', 'Canceled'))	
);
commit;


CREATE TABLE MANAGERS (
EmployeeID VARCHAR2(50) CONSTRAINT managerid_fk REFERENCES EMPLOYEES, 
Workforce_Managed NUMBER(5)
);
commit;


CREATE TABLE ATTENDANTS (
EmployeeID VARCHAR2(50) CONSTRAINT attendantid_fk REFERENCES EMPLOYEES, 
Security_Access_Level VARCHAR2(10) CONSTRAINT security_check CHECK (Security_Access_Level IN ('Online', 'Physical', 'Both'))	
);
commit;


CREATE TABLE CASHIER (
EmployeeID VARCHAR2(50) CONSTRAINT cashierid_fk REFERENCES EMPLOYEES, 
Register_Number NUMBER(3)
);
commit;


CREATE TABLE EMPLOYEE_ADDRESS (
EmployeeID VARCHAR2(50) CONSTRAINT employeeid_fk REFERENCES EMPLOYEES, 
Street VARCHAR2(50),
City VARCHAR2(50),		
Apartment_Number NUMBER(4),		
Zipcode NUMBER(4),
PRIMARY KEY (EmployeeID, Street, City, Apartment_Number, Zipcode)
);
commit;

CREATE TABLE EMPLOYEE_SUPERVISOR (
SupervisorID VARCHAR2(50) CONSTRAINT supervisorid_fk REFERENCES EMPLOYEES,		
Employees_Supervised NUMBER (3)		
);
commit;


CREATE TABLE INVOICE (
Invoice_Number VARCHAR2(50) CONSTRAINT invoiceno_pk PRIMARY KEY,		
Invoice_Date DATE,		
PaymentID VARCHAR2(20) CONSTRAINT invpaymentid_fk REFERENCES Payments,	
Billing_address	VARCHAR2(255),	
Total_Amount NUMBER(10,2)		
);
commit;

CREATE TABLE ORDER_DETAILS (
OrderID	VARCHAR2(20) CONSTRAINT orderdetails_fk REFERENCES Orders,
Quantity NUMBER(3),		
ProductID VARCHAR2(50) CONSTRAINT orderproductid_fk REFERENCES Products,		
Unit_Price NUMBER(10, 2)	
);
commit;


CREATE TABLE STORE_AVAILABILITY (
StoreID	VARCHAR2(50),	
ProductID VARCHAR2(50),
Quantity NUMBER(4),		
sadate DATE,
PRIMARY KEY (StoreID, ProductID, sadate),
FOREIGN KEY (Storeid) REFERENCES Store,
FOREIGN KEY (ProductID) REFERENCES Products
);	
commit;

CREATE TABLE POST_ORDER_STATUS (
RequestID VARCHAR2(50) CONSTRAINT reqid_pk PRIMARY KEY,	
Reason VARCHAR2(255),	
ProductID VARCHAR2(50) CONSTRAINT postorderprodid_fk REFERENCES Products,	
OrderID	VARCHAR2(20) CONSTRAINT postorder_fk REFERENCES Orders,	
Request_Date DATE
);
commit;


CREATE TABLE RETURN_CANCEL (
RequestID VARCHAR2(50) CONSTRAINT reqcanid_fk REFERENCES POST_ORDER_STATUS,
Refund_Date	Date,
RefundID CONSTRAINT ret_fk REFERENCES Refund, 	
Refund_Status VARCHAR2(255)	
);
commit;

CREATE TABLE EXCHANGE_ORDERS (	
RequestID VARCHAR2(50) CONSTRAINT ret_can_fk REFERENCES POST_ORDER_STATUS, 
Exchange_Resolution_Date Date,	
Exchange_Status	VARCHAR2(50) CONSTRAINT exchange_check CHECK (Exchange_Status IN ('Exchange', 'Pending', 'Closed', 'Cancelled')),
Exchange_Method VARCHAR2(50) CONSTRAINT method_check CHECK (Exchange_Method IN ('In-store', 'Pickup'))
);
commit;


CREATE TABLE Reviews (
ReviewID VARCHAR2(50) CONSTRAINT revid_pk PRIMARY KEY,		
ProductID VARCHAR2(50) CONSTRAINT revprodid_fk REFERENCES Products,		
Review VARCHAR2(255)		
);
commit;


CREATE TABLE SUPPLIES (
SupplierID VARCHAR2(50) CONSTRAINT supplyshipno_fk REFERENCES Suppliers,
ProductID VARCHAR2(50) CONSTRAINT supplyprodid_fk REFERENCES Products
);
commit;


CREATE TABLE PURCHASE_DETAILS (
PurchaseID	VARCHAR2(20) CONSTRAINT purchasedetails_fk REFERENCES Purchases,
ProductID VARCHAR2(50) CONSTRAINT purchaseproductid_fk REFERENCES Products,		
Quantity NUMBER(3),		
Unit_Price NUMBER(10, 2)	
);
commit; 


CREATE TABLE SUPPLIES (
SupplierID VARCHAR2(50) CONSTRAINT supplyshipno_fk REFERENCES Suppliers, 
ProductID VARCHAR2(50) CONSTRAINT supplyprodid_fk REFERENCES Products 
); 
commit; 

-------------------------------------------------------------------------------------------------------------------

-- INSERT statements

INSERT INTO Cashier (EmployeeID, Register_Number)
SELECT Employee_ID, ROUND(DBMS_RANDOM.VALUE(1, 99)) AS RegisterNumber
FROM Employees
WHERE Job_Title = 'Cashier';


INSERT INTO Attendants (EmployeeID, Security_Access_Level)
SELECT Employee_ID,
(CASE
    WHEN DBMS_RANDOM.VALUE < 0.33 THEN 'Online'
    WHEN DBMS_RANDOM.VALUE BETWEEN 0.33 AND 0.66 THEN 'Physical'
    ELSE 'Both' END) AS Security_Access_Level
FROM Employees
WHERE Job_Title = 'Attendant';

INSERT INTO Employee_Supervisor (SupervisorID, Employees_Supervised)
SELECT Employee_ID, ROUND(DBMS_RANDOM.VALUE(1, 99)) AS Employees_Supervised
FROM Employees
WHERE Job_Title = 'Supervisor';

-----------------------------------------------------------------------------------------------------------------

-- Additional INSERT statements for Orders table with 30 rows

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O051', 'C1001', 'Pt051', TO_DATE('28-NOV-2023', 'DD-MON-YYYY'), 'Placed', 'Offline', 'S008');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O052', 'C1002', 'Pt052', TO_DATE('08-NOV-2023', 'DD-MON-YYYY'), 'Pending', 'Online', 'S009');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O053', 'C1003', 'Pt053', TO_DATE('24-DEC-2023', 'DD-MON-YYYY'), 'Canceled', 'Offline', 'S008');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O054', 'C1004', 'Pt054', TO_DATE('21-JAN-2024', 'DD-MON-YYYY'), 'Placed', 'Online', 'S011');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O055', 'C1005', 'Pt055', TO_DATE('22-FEB-2024', 'DD-MON-YYYY'), 'Pending', 'Offline', 'S021');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O056', 'C1006', 'Pt056', TO_DATE('06-APR-2022', 'DD-MON-YYYY'), 'Canceled', 'Online', 'S004');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O057', 'C1007', 'Pt057', TO_DATE('05-MAY-2024', 'DD-MON-YYYY'), 'Placed', 'Offline', 'S005');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O058', 'C1008', 'Pt058', TO_DATE('04-JUN-2024', 'DD-MON-YYYY'), 'Pending', 'Online', 'S022');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O059', 'C1009', 'Pt059', TO_DATE('16-JUN-2022', 'DD-MON-YYYY'), 'Canceled', 'Offline', 'S020');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O060', 'C1010', 'Pt060', TO_DATE('21-JUL-2024', 'DD-MON-YYYY'), 'Placed', 'Online', 'S025');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O061', 'C1011', 'Pt061', TO_DATE('15-AUG-2024', 'DD-MON-YYYY'), 'Placed', 'Offline', 'S007');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O062', 'C1012', 'Pt062', TO_DATE('20-SEP-2024', 'DD-MON-YYYY'), 'Pending', 'Online', 'S016');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O063', 'C1013', 'Pt063', TO_DATE('05-OCT-2024', 'DD-MON-YYYY'), 'Canceled', 'Offline', 'S002');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O064', 'C1014', 'Pt064', TO_DATE('10-NOV-2024', 'DD-MON-YYYY'), 'Placed', 'Online', 'S013');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O065', 'C1015', 'Pt065', TO_DATE('15-DEC-2024', 'DD-MON-YYYY'), 'Pending', 'Offline', 'S019');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O066', 'C1016', 'Pt066', TO_DATE('20-JAN-2025', 'DD-MON-YYYY'), 'Canceled', 'Online', 'S004');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O067', 'C1017', 'Pt067', TO_DATE('05-FEB-2025', 'DD-MON-YYYY'), 'Placed', 'Offline', 'S012');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O068', 'C1018', 'Pt068', TO_DATE('10-MAR-2025', 'DD-MON-YYYY'), 'Pending', 'Online', 'S018');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O069', 'C1019', 'Pt069', TO_DATE('15-APR-2025', 'DD-MON-YYYY'), 'Canceled', 'Offline', 'S011');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O070', 'C1020', 'Pt070', TO_DATE('20-MAY-2025', 'DD-MON-YYYY'), 'Placed', 'Online', 'S024');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O071', 'C1011', 'Pt071', TO_DATE('25-JUN-2025', 'DD-MON-YYYY'), 'Pending', 'Online', 'S015');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O072', 'C1012', 'Pt072', TO_DATE('05-JUL-2025', 'DD-MON-YYYY'), 'Canceled', 'Offline', 'S021');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O073', 'C1013', 'Pt073', TO_DATE('15-AUG-2025', 'DD-MON-YYYY'), 'Placed', 'Online', 'S010');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O074', 'C1014', 'Pt074', TO_DATE('25-SEP-2025', 'DD-MON-YYYY'), 'Pending', 'Offline', 'S023');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O075', 'C1015', 'Pt075', TO_DATE('05-OCT-2025', 'DD-MON-YYYY'), 'Canceled', 'Online', 'S007');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O076', 'C1016', 'Pt076', TO_DATE('15-NOV-2025', 'DD-MON-YYYY'), 'Placed', 'Offline', 'S013');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O077', 'C1017', 'Pt077', TO_DATE('25-DEC-2025', 'DD-MON-YYYY'), 'Pending', 'Online', 'S017');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O078', 'C1018', 'Pt078', TO_DATE('05-JAN-2026', 'DD-MON-YYYY'), 'Canceled', 'Offline', 'S008');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O079', 'C1019', 'Pt079', TO_DATE('15-FEB-2026', 'DD-MON-YYYY'), 'Placed', 'Online', 'S019');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O080', 'C1020', 'Pt080', TO_DATE('25-MAR-2026', 'DD-MON-YYYY'), 'Pending', 'Offline', 'S016');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O081', 'C1011', 'Pt081', TO_DATE('10-APR-2026', 'DD-MON-YYYY'), 'Placed', 'Offline', 'S008');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O082', 'C1012', 'Pt082', TO_DATE('20-MAY-2026', 'DD-MON-YYYY'), 'Pending', 'Online', 'S009');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O083', 'C1013', 'Pt083', TO_DATE('30-JUN-2026', 'DD-MON-YYYY'), 'Canceled', 'Offline', 'S008');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O084', 'C1014', 'Pt084', TO_DATE('10-JUL-2026', 'DD-MON-YYYY'), 'Placed', 'Online', 'S013');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O085', 'C1015', 'Pt085', TO_DATE('20-AUG-2026', 'DD-MON-YYYY'), 'Pending', 'Offline', 'S019');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O086', 'C1016', 'Pt086', TO_DATE('30-SEP-2026', 'DD-MON-YYYY'), 'Canceled', 'Online', 'S004');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O087', 'C1017', 'Pt087', TO_DATE('10-OCT-2026', 'DD-MON-YYYY'), 'Placed', 'Offline', 'S012');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O088', 'C1018', 'Pt088', TO_DATE('20-NOV-2026', 'DD-MON-YYYY'), 'Pending', 'Online', 'S018');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O089', 'C1019', 'Pt089', TO_DATE('30-DEC-2026', 'DD-MON-YYYY'), 'Canceled', 'Offline', 'S011');

INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O090', 'C1020', 'Pt090', TO_DATE('10-JAN-2027', 'DD-MON-YYYY'), 'Placed', 'Online', 'S024');

update orders 
set orderstatus = 'Confirmed'
where order_flag = 'Offline';

alter table orders drop constraint orderstatus_nn;

commit;



--------------------------INSERT PAYMENT-----------------------------------------------

-- INSERT statements for Payments table with 40 rows

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt051', TO_DATE('28-NOV-2023', 'DD-MON-YYYY'), 'Credit Card', 50.00, 5.00, 2.00, 'E001', 'Paid', 53.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt052', TO_DATE('08-NOV-2023', 'DD-MON-YYYY'), 'Debit Card', 75.00, 7.50, 3.00, 'E002', 'Pending', 79.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt053', TO_DATE('24-DEC-2023', 'DD-MON-YYYY'), 'Cash', 100.00, 10.00, 5.00, 'E003', 'Paid', 105.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt054', TO_DATE('21-JAN-2024', 'DD-MON-YYYY'), 'Credit Card', 25.00, 2.50, 1.00, 'E004', 'Pending', 26.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt055', TO_DATE('22-FEB-2024', 'DD-MON-YYYY'), 'Debit Card', 45.00, 4.50, 2.00, 'E005', 'Paid', 47.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt056', TO_DATE('06-APR-2022', 'DD-MON-YYYY'), 'Cash', 60.00, 6.00, 3.00, 'E006', 'Pending', 63.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt057', TO_DATE('05-MAY-2024', 'DD-MON-YYYY'), 'Credit Card', 80.00, 8.00, 4.00, 'E007', 'Paid', 84.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt058', TO_DATE('04-JUN-2024', 'DD-MON-YYYY'), 'Debit Card', 90.00, 9.00, 4.50, 'E008', 'Pending', 94.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt059', TO_DATE('16-JUN-2022', 'DD-MON-YYYY'), 'Cash', 120.00, 12.00, 6.00, 'E009', 'Paid', 126.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt060', TO_DATE('21-JUL-2024', 'DD-MON-YYYY'), 'Credit Card', 150.00, 15.00, 7.50, 'E010', 'Pending', 157.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt061', TO_DATE('15-AUG-2024', 'DD-MON-YYYY'), 'Debit Card', 30.00, 3.00, 1.50, 'E011', 'Paid', 31.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt062', TO_DATE('20-SEP-2024', 'DD-MON-YYYY'), 'Cash', 40.00, 4.00, 2.00, 'E012', 'Pending', 42.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt063', TO_DATE('05-OCT-2024', 'DD-MON-YYYY'), 'Credit Card', 60.00, 6.00, 3.00, 'E013', 'Paid', 63.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt064', TO_DATE('10-NOV-2024', 'DD-MON-YYYY'), 'Debit Card', 75.00, 7.50, 3.75, 'E014', 'Pending', 78.75);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt065', TO_DATE('15-DEC-2024', 'DD-MON-YYYY'), 'Cash', 100.00, 10.00, 5.00, 'E015', 'Paid', 105.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt066', TO_DATE('20-JAN-2025', 'DD-MON-YYYY'), 'Credit Card', 25.00, 2.50, 1.25, 'E016', 'Pending', 26.25);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt067', TO_DATE('05-FEB-2025', 'DD-MON-YYYY'), 'Debit Card', 45.00, 4.50, 2.25, 'E017', 'Paid', 47.25);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt068', TO_DATE('10-MAR-2025', 'DD-MON-YYYY'), 'Cash', 60.00, 6.00, 3.00, 'E018', 'Pending', 63.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt069', TO_DATE('15-APR-2025', 'DD-MON-YYYY'), 'Credit Card', 80.00, 8.00, 4.00, 'E019', 'Paid', 84.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt070', TO_DATE('20-MAY-2025', 'DD-MON-YYYY'), 'Debit Card', 90.00, 9.00, 4.50, 'E020', 'Pending', 94.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt071', TO_DATE('25-JUN-2025', 'DD-MON-YYYY'), 'Cash', 120.00, 12.00, 6.00, 'E021', 'Paid', 126.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt072', TO_DATE('05-JUL-2025', 'DD-MON-YYYY'), 'Credit Card', 150.00, 15.00, 7.50, 'E022', 'Pending', 157.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt073', TO_DATE('15-AUG-2025', 'DD-MON-YYYY'), 'Debit Card', 30.00, 3.00, 1.50, 'E023', 'Paid', 31.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt074', TO_DATE('25-SEP-2025', 'DD-MON-YYYY'), 'Cash', 40.00, 4.00, 2.00, 'E024', 'Pending', 42.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt075', TO_DATE('05-OCT-2025', 'DD-MON-YYYY'), 'Credit Card', 60.00, 6.00, 3.00, 'E025', 'Paid', 63.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt076', TO_DATE('15-NOV-2025', 'DD-MON-YYYY'), 'Debit Card', 75.00, 7.50, 3.75, 'E026', 'Pending', 78.75);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt077', TO_DATE('25-DEC-2025', 'DD-MON-YYYY'), 'Cash', 100.00, 10.00, 5.00, 'E027', 'Paid', 105.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt078', TO_DATE('05-JAN-2026', 'DD-MON-YYYY'), 'Credit Card', 25.00, 2.50, 1.25, 'E028', 'Pending', 26.25);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt079', TO_DATE('15-FEB-2026', 'DD-MON-YYYY'), 'Debit Card', 45.00, 4.50, 2.25, 'E029', 'Paid', 47.25);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt080', TO_DATE('25-MAR-2026', 'DD-MON-YYYY'), 'Cash', 60.00, 6.00, 3.00, 'E030', 'Pending', 63.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt081', TO_DATE('10-APR-2026', 'DD-MON-YYYY'), 'Credit Card', 80.00, 8.00, 4.00, 'E031', 'Paid', 84.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt082', TO_DATE('20-MAY-2026', 'DD-MON-YYYY'), 'Debit Card', 90.00, 9.00, 4.50, 'E032', 'Pending', 94.50);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt083', TO_DATE('30-JUN-2026', 'DD-MON-YYYY'), 'Cash', 120.00, 12.00, 6.00, 'E033', 'Paid', 126.00);

INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt084', TO_DATE('10-JUL-2026', 'DD-MON-YYYY'), 'Credit Card', 150.00, 15.00, 7.50, 'E034', 'Pending', 157.50);

commit;


----------INSERT reviews -----------------------
-- Additional Insert statements for Review table with product IDs P091 to P097

-- P091
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('23', 'P091', 'Impressed with the quality. Fast delivery!', TO_DATE('30-JUN-2023', 'DD-MON-YYYY') + 1, 'N');

-- P092
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('24', 'P092', 'Great product, exceeded my expectations.', TO_DATE('12-NOV-2023', 'DD-MON-YYYY') + 1, 'N');

-- P093
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('25', 'P093', 'The product is fantastic. Arrived on time.', TO_DATE('10-JUN-2024', 'DD-MON-YYYY') + 1, 'N');

-- P094
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('26', 'P094', 'Highly recommended. Excellent service.', TO_DATE('15-NOV-2023', 'DD-MON-YYYY') + 1, 'N');

-- P095
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('27', 'P095', 'Satisfied with the purchase. Good quality.', TO_DATE('07-JUN-2024', 'DD-MON-YYYY') + 1, 'N');

-- P096
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('28', 'P096', 'Product as described. Quick delivery.', TO_DATE('31-OCT-2023', 'DD-MON-YYYY') + 1, 'N');

-- P097
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('29', 'P097', 'Excellent service. Timely delivery.', TO_DATE('24-JAN-2023', 'DD-MON-YYYY') + 1, 'N');


-- P084
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('30', 'P084', 'Impressive product! Delivered on time.', TO_DATE('11-MAY-2024', 'DD-MON-YYYY') + 1, 'N');

-- P085
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('31', 'P085', 'Satisfied with the purchase. Good quality.', TO_DATE('27-JUL-2024', 'DD-MON-YYYY') + 1, 'N');

-- P086
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('32', 'P086', 'Excellent service. Quick delivery.', TO_DATE('13-JAN-2023', 'DD-MON-YYYY') + 1, 'N');

-- P087
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('33', 'P087', 'Highly recommended. Fast shipping.', TO_DATE('19-MAY-2023', 'DD-MON-YYYY') + 1, 'N');

-- P088
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('34', 'P088', 'Product as described. Timely delivery.', TO_DATE('18-AUG-2023', 'DD-MON-YYYY') + 1, 'N');

-- P089
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('35', 'P089', 'Satisfied with the quality. Good service.', TO_DATE('30-OCT-2023', 'DD-MON-YYYY') + 1, 'N');

-- P090
INSERT INTO ReviewS (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('36', 'P090', 'Product exceeded expectations. Prompt delivery.', TO_DATE('25-JAN-2024', 'DD-MON-YYYY') + 1, 'N');

alter table reviews drop constraint prod_review_fk;

alter table reviews modify (constraint prod_review_fk REFERENCES PRODUCT);

ALTER TABLE reviews
add CONSTRAINT prod_review_fk FOREIGN KEY (productid) REFERENCES PRODUCT;




-------------------------INSERT PAYMENT 41-50-----------------------------------------------
-- Insert statements for Payments table with PAYMENTID from Pt041 to Pt050

-- Pt041
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt041', TO_DATE('01-JAN-2023', 'DD-MON-YYYY'), 'Credit Card', 100.00, 5.00, 10.00, 'E001', 'Paid', 115.00);

-- Pt042
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt042', TO_DATE('10-JAN-2023', 'DD-MON-YYYY'), 'Credit Card', 150.00, 7.50, 15.00, 'E002', 'Paid', 172.50);

-- Pt043
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt043', TO_DATE('15-FEB-2023', 'DD-MON-YYYY'), 'Cash', 120.00, 6.00, 12.00, 'E003', 'Paid', 138.00);

-- Pt044
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt044', TO_DATE('20-MAR-2023', 'DD-MON-YYYY'), 'Credit Card', 90.00, 4.50, 9.00, 'E004', 'Paid', 104.50);

-- Pt045
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt045', TO_DATE('25-APR-2023', 'DD-MON-YYYY'), 'Credit Card', 110.00, 5.50, 11.00, 'E005', 'Paid', 126.50);

-- Pt046
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt046', TO_DATE('01-MAY-2023', 'DD-MON-YYYY'), 'Cash', 80.00, 4.00, 8.00, 'E006', 'Paid', 92.00);

-- Pt047
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt047', TO_DATE('10-JUN-2023', 'DD-MON-YYYY'), 'Credit Card', 130.00, 6.50, 13.00, 'E007', 'Paid', 149.50);

-- Pt048
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt048', TO_DATE('15-JUL-2023', 'DD-MON-YYYY'), 'Credit Card', 95.00, 4.75, 9.50, 'E008', 'Paid', 109.25);

-- Pt049
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt049', TO_DATE('20-AUG-2023', 'DD-MON-YYYY'), 'Cash', 75.00, 3.75, 7.50, 'E009', 'Paid', 86.25);

-- Pt050
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt050', TO_DATE('25-SEP-2023', 'DD-MON-YYYY'), 'Credit Card', 160.00, 8.00, 16.00, 'E010', 'Paid', 184.00);


----------------------INSERT ORDER 41-5-----------------------------------

-- Insert statements for Orders table with ORDERID from O041 to O050

-- O041
-- Modified Insert statements for Orders table with ORDERID from O041 to O050

-- O041
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O041', 'C1001', 'Pt041', TO_DATE('01-JAN-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O042
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O042', 'C1002', 'Pt042', TO_DATE('10-JAN-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S001');

-- O043
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O043', 'C1003', 'Pt043', TO_DATE('15-FEB-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O044
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O044', 'C1004', 'Pt044', TO_DATE('20-MAR-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S002');

-- O045
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O045', 'C1005', 'Pt045', TO_DATE('25-APR-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O046
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O046', 'C1006', 'Pt046', TO_DATE('01-MAY-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S004');

-- O047
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O047', 'C1007', 'Pt047', TO_DATE('10-JUN-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O048
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O048', 'C1008', 'Pt048', TO_DATE('15-JUL-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S006');

-- O049
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O049', 'C1009', 'Pt049', TO_DATE('20-AUG-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O050
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O050', 'C1010', 'Pt050', TO_DATE('25-SEP-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S011');

commit;


-----INSERT PAYMENT MISSING ----------------

-- Insert statements for Payments table corresponding to Orders with ORDERID 52, 55, 58, 61, 64, 67, 70, 73, 76

-- Insert statements for Payments table corresponding to Orders with ORDERID 52, 55, 58, 61, 64, 67, 70, 73, 76

-- Pt052
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt052', TO_DATE('08-NOV-2023', 'DD-MON-YYYY'), 'Credit Card', 100.00, 5.00, 10.00, 'E001', 'Paid', 115.00);

-- Pt055
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt055', TO_DATE('22-FEB-2023', 'DD-MON-YYYY'), 'Cash', 120.00, 6.00, 15.00, 'E002', 'Paid', 111.00);

-- Pt058
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt058', TO_DATE('04-JUN-2023', 'DD-MON-YYYY'), 'Credit Card', 90.00, 4.50, 9.00, 'E003', 'Paid', 104.50);

-- Pt061
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt061', TO_DATE('15-AUG-2023', 'DD-MON-YYYY'), 'Cash', 110.00, 5.50, 11.00, 'E004', 'Paid', 123.50);

-- Pt064
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt064', TO_DATE('10-NOV-2023', 'DD-MON-YYYY'), 'Credit Card', 80.00, 4.00, 8.00, 'E005', 'Paid', 92.00);

-- Pt067
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt067', TO_DATE('05-FEB-2023', 'DD-MON-YYYY'), 'Cash', 95.00, 4.75, 9.50, 'E006', 'Paid', 109.25);

-- Pt070
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt070', TO_DATE('20-MAY-2023', 'DD-MON-YYYY'), 'Credit Card', 105.00, 5.25, 10.50, 'E007', 'Paid', 120.75);

-- Pt073
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt073', TO_DATE('15-AUG-2023', 'DD-MON-YYYY'), 'Cash', 88.00, 4.40, 8.80, 'E008', 'Paid', 101.20);

-- Pt076
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt076', TO_DATE('15-NOV-2023', 'DD-MON-YYYY'), 'Credit Card', 75.00, 3.75, 7.50, 'E009', 'Paid', 86.25);


---------------------INERT MISSING ORDERS-------------------------

-- Insert statements for Orders table with ORDERID 52, 55, 58, 61, 64, 67, 70, 73, 76

-- O052
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O052', 'C1002', 'Pt052', TO_DATE('08-NOV-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O055
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O055', 'C1005', 'Pt055', TO_DATE('22-FEB-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S021');

-- O058
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O058', 'C1008', 'Pt058', TO_DATE('04-JUN-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O061
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O061', 'C1011', 'Pt061', TO_DATE('15-AUG-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S007');

-- O064
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O064', 'C1014', 'Pt064', TO_DATE('10-NOV-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O067
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O067', 'C1017', 'Pt067', TO_DATE('05-FEB-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S012');

-- O070
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O070', 'C1020', 'Pt070', TO_DATE('20-MAY-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O073
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O073', 'C1013', 'Pt073', TO_DATE('15-AUG-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S002');

-- O076
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O076', 'C1016', 'Pt076', TO_DATE('15-NOV-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

COMMIT;


----INSERT PAYMENT 79/82---------------------------

-- Insert statements for Payments corresponding to Orders with ORDERIDs 79 and 82

-- Pt079
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt079', TO_DATE('15-FEB-2023', 'DD-MON-YYYY'), 'Credit Card', 95.00, 4.75, 9.50, 'E001', 'Paid', 109.25);

-- Pt082
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt082', TO_DATE('20-MAY-2023', 'DD-MON-YYYY'), 'Cash', 88.00, 4.40, 8.80, 'E002', 'Paid', 101.20);





----------INSERT ORDERS 79,82
-- Insert statements for Orders with ORDERIDs 79 and 82

-- O079
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O079', 'C1019', 'Pt079', TO_DATE('15-FEB-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O082
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O082', 'C1012', 'Pt082', TO_DATE('20-MAY-2023', 'DD-MON-YYYY'), 'Confirmed', 'Offline', 'S009');


commit;

------------PAYMENTS 85-100 ONLINE------------------
-- Insert statements for Payments with PAYMENTIDs Pt085 to Pt100 (revised)

-- Pt085
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt085', TO_DATE('05-OCT-2022', 'DD-MON-YYYY'), 'Credit Card', 100.00, 5.00, 10.00, 'E001', 'Paid', 95.00);

-- Pt086
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt086', TO_DATE('15-NOV-2022', 'DD-MON-YYYY'), 'Credit Card', 80.00, 4.00, 8.00, 'E002', 'Paid', 76.00);

-- Pt087
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt087', TO_DATE('25-DEC-2022', 'DD-MON-YYYY'), 'PayPal', 120.00, 6.00, 12.00, 'E003', 'Paid', 114.00);

-- Pt088
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt088', TO_DATE('05-JAN-2023', 'DD-MON-YYYY'), 'Credit Card', 90.00, 4.50, 9.00, 'E004', 'Paid', 85.50);

-- Pt089
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt089', TO_DATE('15-FEB-2023', 'DD-MON-YYYY'), 'PayPal', 110.00, 5.50, 11.00, 'E005', 'Paid', 104.50);

-- Pt090
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt090', TO_DATE('25-MAR-2023', 'DD-MON-YYYY'), 'PayPal', 95.00, 4.75, 9.50, 'E006', 'Paid', 90.25);

-- Pt091
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt091', TO_DATE('10-APR-2023', 'DD-MON-YYYY'), 'Credit Card', 120.00, 6.00, 12.00, 'E007', 'Paid', 114.00);

-- Pt092
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt092', TO_DATE('20-MAY-2023', 'DD-MON-YYYY'), 'Credit Card', 85.00, 4.25, 8.50, 'E008', 'Paid', 80.25);

-- Pt093
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt093', TO_DATE('30-JUN-2023', 'DD-MON-YYYY'), 'PayPal', 100.00, 5.00, 10.00, 'E009', 'Paid', 95.00);

-- Pt094
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt094', TO_DATE('10-JUL-2023', 'DD-MON-YYYY'), 'Credit Card', 75.00, 3.75, 7.50, 'E010', 'Paid', 70.25);

-- Pt095
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt095', TO_DATE('20-AUG-2023', 'DD-MON-YYYY'), 'PayPal', 110.00, 5.50, 11.00, 'E011', 'Paid', 104.50);

-- Pt096
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt096', TO_DATE('30-SEP-2023', 'DD-MON-YYYY'), 'PayPal', 90.00, 4.50, 9.00, 'E012', 'Paid', 85.50);

-- Pt097
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt097', TO_DATE('10-OCT-2023', 'DD-MON-YYYY'), 'Credit Card', 105.00, 5.25, 10.50, 'E013', 'Paid', 99.75);

-- Pt098
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt098', TO_DATE('20-NOV-2023', 'DD-MON-YYYY'), 'PayPal', 95.00, 4.75, 9.50, 'E014', 'Paid', 90.25);

-- Pt099
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt099', TO_DATE('30-DEC-2023', 'DD-MON-YYYY'), 'PayPal', 115.00, 5.75, 11.50, 'E015', 'Paid', 109.25);

-- Pt100
INSERT INTO Payments (PAYMENTID, PAYMENTDATE, PAYMENT_METHOD, PAYMENT_AMOUNT, TAX, DISCOUNT, EMPLOYEEID, PAYMENT_STATUS, FINAL_AMOUNT)
VALUES ('Pt100', TO_DATE('10-JAN-2024', 'DD-MON-YYYY'), 'Credit Card', 80.00, 4.00, 8.00, 'E016', 'Paid', 76.00);

-------------------ORDER 85-100 ONLINE-----------------------

-- Insert statements for Orders with ORDERIDs O085 to O100

-- O085
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O085', 'C1015', 'Pt085', TO_DATE('05-OCT-2022', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O086
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O086', 'C1016', 'Pt086', TO_DATE('15-NOV-2022', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O087
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O087', 'C1017', 'Pt087', TO_DATE('25-DEC-2022', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O088
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O088', 'C1018', 'Pt088', TO_DATE('05-JAN-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O089
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O089', 'C1019', 'Pt089', TO_DATE('15-FEB-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O090
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O090', 'C1020', 'Pt090', TO_DATE('25-MAR-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O091
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O091', 'C1011', 'Pt091', TO_DATE('10-APR-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O092
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O092', 'C1012', 'Pt092', TO_DATE('20-MAY-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O093
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O093', 'C1013', 'Pt093', TO_DATE('30-JUN-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O094
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O094', 'C1014', 'Pt094', TO_DATE('10-JUL-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O095
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O095', 'C1015', 'Pt095', TO_DATE('20-AUG-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O096
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O096', 'C1016', 'Pt096', TO_DATE('30-SEP-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O097
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O097', 'C1017', 'Pt097', TO_DATE('10-OCT-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O098
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O098', 'C1018', 'Pt098', TO_DATE('20-NOV-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O099
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O099', 'C1019', 'Pt099', TO_DATE('30-DEC-2023', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

-- O100
INSERT INTO Orders (ORDERID, CUSTOMERID, PAYMENTID, ORDERDATE, ORDERSTATUS, ORDER_FLAG, STOREID)
VALUES ('O100', 'C1020', 'Pt100', TO_DATE('10-JAN-2024', 'DD-MON-YYYY'), 'Confirmed', 'Online', NULL);

commit;

-----------------INSERT REVIEW-------------------------------------

-- Reviews for P002 - Professional Hammer Drill

INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('06', 'P002', 'Solid construction and powerful performance. Best drill for professionals.', TO_DATE('15-NOV-2023', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('07', 'P002', 'Great value for the money. Used it for a construction project, and it exceeded expectations.', TO_DATE('25-DEC-2023', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('08', 'P002', 'Easy to handle and very efficient. The variable speed control is a useful feature.', TO_DATE('05-JAN-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('09', 'P002', 'Good battery life and quick charging. Perfect for professional use.', TO_DATE('15-FEB-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('10', 'P002', 'Excellent build quality. Used it extensively, and its still going strong.', TO_DATE('25-MAR-2024', 'DD-MON-YYYY'), 'N');

-- Reviews for P003 - Compact Electric Drill
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('11', 'P003', 'Compact size but powerful performance. Great for DIY projects.', TO_DATE('10-APR-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('12', 'P003', 'Easy to control and lightweight. Ideal for home use.', TO_DATE('20-MAY-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('13', 'P003', 'Versatile drill with various settings. The LED light is a useful addition.', TO_DATE('30-JUN-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('14', 'P003', 'Durable build and comfortable grip. Highly recommend for small projects.', TO_DATE('10-JUL-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('15', 'P003', 'Good battery life. Used it for woodworking, and it performed well.', TO_DATE('20-AUG-2024', 'DD-MON-YYYY'), 'N');

-- Reviews for P014 - Car Polisher and Buffer
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('16', 'P014', 'Outstanding performance on my car. It brought out a fantastic shine.', TO_DATE('30-SEP-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('17', 'P014', 'Easy to use and maneuver. Polished my car quickly with excellent results.', TO_DATE('10-OCT-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('18', 'P014', 'Quiet operation and effective polishing. Happy with the purchase.', TO_DATE('20-NOV-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('19', 'P014', 'Solid build quality. Used it for detailing and got professional-level results.', TO_DATE('30-DEC-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('20', 'P014', 'Versatile polisher with different speed settings. Recommend it for car enthusiasts.', TO_DATE('10-JAN-2025', 'DD-MON-YYYY'), 'N');

-- Reviews for P016 - Drill Bit Set (50 pieces)
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('21', 'P016', 'Extensive set with a wide range of drill bits. Great for various projects.', TO_DATE('28-OCT-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('22', 'P016', 'Durable bits that stayed sharp after multiple uses. Good value for the money.', TO_DATE('08-NOV-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('23', 'P016', 'Organized case makes it easy to find the right drill bit. Recommended for DIYers.', TO_DATE('25-SEP-2024', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('24', 'P016', 'High-quality materials used in the bits. Impressed with the performance.', TO_DATE('20-JAN-2025', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('25', 'P016', 'Excellent variety for different materials. A must-have for any toolbox.', TO_DATE('21-FEB-2025', 'DD-MON-YYYY'), 'N');

-- Reviews for P033 - Concrete Blocks (8x8x16 in)
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('26', 'P033', 'Sturdy and reliable concrete blocks. Used them for building a wall, and they held up well.', TO_DATE('06-APR-2022', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('27', 'P033', 'Good quality blocks for construction. Pleased with the results of my project.', TO_DATE('14-OCT-2023', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('28', 'P033', 'Easy to work with and stack. Used them for a garden project with excellent outcomes.', TO_DATE('02-OCT-2023', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('29', 'P033', 'Solid blocks that exceeded my expectations. Will buy again for future projects.', TO_DATE('16-JUN-2022', 'DD-MON-YYYY'), 'N');
INSERT INTO Reviews (REVIEWID, PRODUCTID, REVIEW_DESCRIPTION, REVIEW_DATE, REPORTED_FLAG)
VALUES ('30', 'P033', 'Good value for bulk purchase. Arrived in excellent condition and on time.', TO_DATE('22-OCT-2023', 'DD-MON-YYYY'), 'N');




commit;

















